### ISSUE TITLE
Choose technologies

### ISSUE THREAD

**Issue by mathiassmichno** [randomchain/master-thesis-paper#7]
Section about which technologies we will use in the beacon implementation.
Maybe this could include address the use of blockchain?

Loose notes:

- Python
- C extensions
- Message Queue (e.g. RabbitMQ, ZeroMQ, Kafka)
- Publishing tech (webserver etc.?)
- Input sources (usability, reliability, auditing ...)
- Commitment (hashing, bottleneck, merkle tree)

**Comment by mathiassmichno** [comment]
ZeroMQ

**Comment by SebRKri** [comment]
Helsides annonce i avis
